# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc99d29513eb861e6251f11c6e6d877cd4155565952e5119c95d6f4d10c378d8d0b944c8eafdf5b6d7229e905635fd1ad1786c7512384907948d4232c3cf8cb

test:
  secret_key_base: f39bb2f68054230dc196a1394c9627a8fa2d463f86eb35b2af367c68f372a464c25d8e5d1bec15bbc536e97364e0f1f8e3768c84a08a83832f1f23500b815ef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
